version: "3.9"

services:
    parcelpulse:
        image: node:20
        container_name: parcelpulse-ctf-escape
        working_dir: /app
        volumes:
            - ./app:/app
        command: sh -c "apt-get update && apt-get install -y iputils-ping && npm install && node server.js"        
        ports:
            - "3001:3001"
        environment:
            NODE_ENV: production
        restart: unless-stopped
